Update patch set 2
Patch Set 2: Verified-1

Build Failed 

https://rhos-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/gate-infrared-external-plugin-patch-components/184/ : Gate FAILED, you can retrigger all tests with comment "recheck", or comment "recheck infrared-external-plugin-pipeline" to retrigger only this test <<<
FAILURE:
>>>

Groovy error, likely misuse of double quotes instead of single ones. ( https://rhos-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/gate-infrared-external-plugin-patch-components/184/ )

Cannot contact qe-generic-tlv-01: java.lang.InterruptedException ( https://rhos-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/gate-infrared-external-plugin-patch-components/184/ )

ERROR: Publisher �Publish JUnit test result report� failed: No test report files were found. Configuration error? ( https://rhos-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/gate-infrared-external-plugin-patch-components/184/ )

Patch-set: 2
Tag: jenkins-gerrit-trigger
Reviewer: rhosqeauto <1008131@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Verified=-1