No need in rhelosp-rhel-pending
In fact it causes dep problem. At the patch component stage
the rpm-4.11.3-40 while undercloud stage expects 4.11.3-35.

TASK [install rhosp-release] ***************************************************
task path: infrared/plugins/tripleo-undercloud/deploy.yml:75

Error: Package: rpm-build-4.11.3-35.el7.x86_64 (rhelosp-rhel-7.6-server)
           Requires: rpm = 4.11.3-35.el7
           Installed: rpm-4.11.3-40.el7.x86_64 (@rhelosp-rhel-pending)
               rpm = 4.11.3-40.el7